# Generated by Django 3.2 on 2021-07-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210625_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='place_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True,  serialize=False, verbose_name='ID')),
                ('Items_json', models.CharField(max_length=5000)),
                ('Name', models.CharField(max_length=90)),
                ('Email', models.CharField(max_length=111)),
                ('Address', models.CharField(max_length=111)),
                ('City', models.CharField(max_length=111)),
                ('State', models.CharField(max_length=111)),
                ('Zip_code', models.CharField(max_length=111)),
                ('Phone', models.CharField( max_length=111)),
            ],
        ),
    ]
