# Generated by Django 3.2 on 2021-07-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_order',
            name='Items_json',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
