# Generated by Django 3.2 on 2021-07-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_place_order_items_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_order',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='place_order',
            name='Items_json',
            field=models.CharField(max_length=5000),
        ),
    ]
